name: flutter_dashboard
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.4
  cloud_firestore_web: ^3.10.4
  firebase_database: ^10.4.6 
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  fl_chart: ^0.62.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 900
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
